kyc_form_title:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'One Step Away to Access the Token Sale'

kyc_form_subtitle:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'You will need the following items to complete the registration'

eth_address_instruction_text:
  data_kind: 'html'
  validations:
    required: 0
    max_length: 200
  default_value: 'Make sure to use your Ethereum Wallet address and not addresses<br>from exchanges like Coinbase, Poloniex, Kraken.'

document_id_instruction_text:
  data_kind: 'html'
  validations:
    required: 0
    max_length: 200
  default_value: 'A valid government issued passport is required. A national ID<br>or a license are not accepted for the verification process.'

show_kyc_confirm_popup:
  data_kind: 'number'
  validations:
    required: 1
    includes: [0, 1]
  default_value: 1

kyc_form_popup_checkboxes:
  data_kind: 'array'
  validations:
    max_count: 10
    required: 0
    max_length: 400
  element:
    data_kind: 'html'
    validations:
      max_length: 400
  default_value: ['All the information I have entered is true and complete.',
                  'I am not restricted under any law from providing this information or purchasing Company Tokens.',
                  'I act on my own behalf, unless I have notified you in writing.',
                  'I have read, understood and agree to <a href="https://domain.com/privacy.html" rel="nofollow" target="_blank" >Privacy Policy</a>. I acknowledge
                    this may change. I also understand that any purchase of Company Tokens will be subject to additional terms and conditions.',
                  'I agree that I will send payment from, and receive any Company Tokens to, the digital wallet address I have entered on this website.']