policy_texts:
  data_kind: 'array'
  validations:
    required: 1
    max_count: 4
    min_count: 2
    max_length: 400
  element:
    data_kind: 'html'
    validations:
      max_length: 400
      min_length: 1
  default_value: ['By checking this box, you agree to our <a href="https://domain.com/terms-and-conditions.html"
                  title="Terms and Conditions" target="_blank" rel="nofollow" >Terms and Conditions</a>
                  and acknowledge and consent to our <a href="https://domain.com/privacy.html"
                  title="Privacy Policy" target="_blank">Privacy Policy</a>']