policy-text:
  data_kind: 'text'
  validations:
    mandatory: 1
  default_value: 'By checking this box, you agree to our <a href="https://domain.com/terms-and-conditions.html"
                  title="Terms and Conditions" target="_blank" rel="nofollow" >Terms and Conditions</a>
                  and acknowledge and consent to our <a href="https://domain.com/privacy.html"
                  title="Privacy Policy" target="_blank">Privacy Policy</a>'

policy-text-link-color:
  data_kind: 'text'
  validations:
    mandatory: 1
  default_value: '#FEB202'