policy_texts:
  data_kind: 'array'
  validations:
    required: 1
    max_count: 4
    min_count: 1
    max_length: 400
    min_length: 1
  element:
    data_kind: 'html'
    validations:
      required: 1
  default_value: ['I agree to the Terms &amp; Conditions and Privacy Policy']