company_logo:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'https://s3.amazonaws.com/asset.pepomail.com/common-assets/images/logo-watermark-black-final.png'

company_logo_size_percent:
  data_kind: 'number'
  validations:
    required: 0
  default_value: 100

company_favicon:
  data_kind: 'text'
  validations:
    required: 0
  default_value: 'https://s3.amazonaws.com/asset.pepomail.com/common-assets/images/logo-watermark-black-final.png'

background_gradient:
  data_kind: 'text'
  validations:
    required: 1
  default_value: '(to bottom, #000000 0%, #ffffff 135px, #ffffff 100%)'

primary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#000000'

primary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

primary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

primary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

primary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

primary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

secondary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

secondary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FFFFFF'

secondary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#000000'

secondary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#000000'

secondary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

secondary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

footer_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FEB202'

footer_link_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#FFFFFF'

footer_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: '#000000'

footer_text:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'Copyright &copy; 2018 Company. All Rights Reserved. <a href="https://domain.com/terms-and-conditions.html"
                    title="Terms and Conditions" target="_blank" rel="nofollow" >Terms and Conditions</a> & <a href="https://domain.com/privacy.html"
                    title="Privacy Policy" target="_blank" rel="nofollow">Privacy Policy</a>'

terms_condition_link:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'https://domain.com/terms-n-conditions.html'

gtm_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''

fb_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''

fb_pixel_version:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''