company_logo:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'https://d27ixhmpjdysfk.cloudfront.net/c_assets/company/company-logo.png'

company_logo_size_percent:
  data_kind: 'number'
  validations:
    required: 0
  default_value: 15

company_favicon:
  data_kind: 'text'
  validations:
    required: 0
  default_value: 'https://d27ixhmpjdysfk.cloudfront.net/c_assets/company/company-logo.png'

background_gradient:
  data_kind: 'array'
  validations:
    required: 1
  default_value: [{color: "rgb(243,249,244)", gradient: 0}, {color: "rgb(255,255,255)", gradient: 20}]

primary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

primary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(228,176,48)'

primary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(228,176,48)'

primary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

primary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(212,163,38)'

primary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(212,163,38)'

secondary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

secondary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

secondary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

footer_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(158,169,167)'

footer_link_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(158,169,167)'

footer_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(229,239,232)'

footer_text:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'Copyright &copy; 2018 Company. All Rights Reserved. <a href="https://domain.com/terms-and-conditions.html"
                    title="Terms and Conditions" target="_blank" rel="nofollow" >Terms and Conditions</a> & <a href="https://domain.com/privacy.html"
                    title="Privacy Policy" target="_blank" rel="nofollow">Privacy Policy</a>'

terms_condition_link:
  data_kind: 'text'
  validations:
    required: 1
  default_value: 'https://domain.com/terms-n-conditions.html'

gtm_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''

fb_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''

fb_pixel_version:
  data_kind: 'text'
  validations:
    required: 0
  default_value: ''