company_logo:
  data_kind: 'text'
  validations:
    required: 1
    min_bytes: 1024
    max_bytes: 2097152
    accept: ['image/jpeg', 'image/png', 'image/jpg']
  default_value: 'c_assets/sta/default/logo.jpeg'

company_logo_size_percent:
  data_kind: 'number'
  validations:
    required: 1
    max: 100
    min: 1
  default_value: 30

company_favicon:
  data_kind: 'text'
  validations:
    required: 0
    min_bytes: 1024
    max_bytes: 204800
    accept: ['image/jpeg', 'image/png', 'image/jpg', 'image/x-icon']
  default_value: ''

background_gradient:
  data_kind: 'array'
  validations:
    required: 1
    max_count: 3
    min_count: 2
  element:
    color:
      data_kind: 'color'
      validations:
        required: 1
    gradient:
      data_kind: 'number'
      validations:
        required: 1
        max: 100
        min: 0
  default_value: [{color: "rgb(243, 249, 244)", gradient: 40}, {color: "rgb(215, 232, 218)", gradient: 50}]

primary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

primary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(228,176,48)'

primary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(228,176,48)'

primary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

primary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(212,163,38)'

primary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(212,163,38)'

secondary_button_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

secondary_button_border_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_text_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(255,255,255)'

secondary_button_background_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

secondary_button_border_color_active:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(127,145,131)'

footer_text_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(158,169,167)'

footer_link_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(158,169,167)'

footer_background_color:
  data_kind: 'color'
  validations:
    required: 1
  default_value: 'rgb(229,239,232)'

footer_text:
  data_kind: 'html'
  validations:
    required: 1
    max_length: 400
    min_length: 1
  default_value: 'Copyright © 2018 Company. All Rights Reserved. Terms &amp; Conditions and Privacy Policy'

terms_condition_link:
  data_kind: 'link'
  validations:
    required: 1
    max_length: 250
    min_length: 1
  default_value: 'https://domain.com/terms-n-conditions.html'

gtm_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
    max_length: 50
  default_value: ''

fb_pixel_id:
  data_kind: 'text'
  validations:
    required: 0
    max_length: 50
  default_value: ''

fb_pixel_version:
  data_kind: 'text'
  validations:
    required: 0
    max_length: 50
  default_value: ''