invalid_order:
  parameter: 'order'
  msg: "order in 'desc' (default) or 'asc' order."

invalid_page_number:
  parameter: 'page_number'
  msg: "Page number is invalid."

invalid_allowed_keys:
  parameter: 'set_allowed_keys'
  message: "Invalid field selected."

invalid_page_size:
  parameter: 'page_size'
  msg: "Page size is invalid."

invalid_user_id:
  parameter: 'user_id'
  msg: "user id is invalid."

invalid_email:
  parameter: 'email'
  msg: "email is invalid."

missing_email:
  parameter: 'email'
  msg: "email is mandatory."

user_already_present:
  parameter: 'email'
  msg: "user with this email already exist."

missing_client_id:
  parameter: 'client_id'
  msg: "client_id is mandatory."

missing_user_id:
  parameter: 'user_id'
  msg: "user_id is mandatory."

missing_id:
   parameter: 'id'
   msg: "id is mandatory."

invalid_id:
  parameter: 'id'
  msg: "id is invalid."

invalid_ethereum_address:
   parameter: 'ethereum_address'
   msg: "ethereum_address is invalid."

missing_ethereum_address:
   parameter: 'ethereum_address'
   msg: "ethereum_address is missing."

missing_pdfs:
   parameter: 'pdfs'
   msg: "pdfs is missing."

invalid_pdfs:
   parameter: 'pdfs'
   msg: "pdfs is invalid. Only 'application/pdf' content type is supported."

missing_images:
   parameter: 'images'
   msg: "images is missing."

invalid_images:
   parameter: 'images'
   msg: "images is invalid. Only 'image/jpeg', 'image/png', 'image/jpg' content types are supported."

invalid_filters:
   parameter: 'filters'
   msg: "filters is invalid."
