constants:
  kms:
    login:
      arn: <%= ENV['STA_LOGIN_KMS_ARN']%>
      id: <%= ENV['STA_LOGIN_KMS_ID']%>
    kyc:
      arn: <%= ENV['STA_KYC_KMS_ARN']%>
      id: <%= ENV['STA_KYC_KMS_ID']%>

  cynopsis:
    base_url: <%= ENV['STA_CYNOPSIS_BASE_URL']%>
    token: <%= ENV['STA_CYNOPSIS_TOKEN']%>
    domain_name: <%= ENV['STA_CYNOPSIS_DOMAIN_NAME']%>

  aws:
    region: <%= ENV['STA_DEFAULT_AWS_REGION']%>
    admin:
      access_key: <%= ENV['STA_ADMIN_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_ADMIN_AWS_SECRET_KEY']%>
    user:
      access_key: <%= ENV['STA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_USER_AWS_SECRET_KEY']%>

  pepo_campaigns:
    api:
      key: <%= ENV['STA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['STA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['STA_CAMPAIGN_BASE_URL']%>
      version: 'v1'
    list_ids:
      master_list: <%= ENV['STA_CAMPAIGN_MASTER_LIST']%>

  redis:
    url: <%= ENV['STA_REDIS_ENDPOINT'] %>

  s3:
    kyc_bucket: <%= ENV['STA_KYC_S3_BUCKET_NAME']%>

  local_path:
    geo_ip_file: <%= ENV['STA_GEOIP_FILE_WITH_PATH'] %>

  st_token_sale:
    critical_details:
      active_status: <%= ENV['STA_TOKEN_SALE_ACTIVE_STATUS']%>
      foundation_ethereum_address: <%= ENV['STA_FOUNDATION_ETHEREUM_ADDRESS']%>
    user_register_dates:
      pre_sale_register_end_date:  <%= ENV['STA_PRE_SALE_REGISTER_END_DATE'] %>
    sale_dates:
      pre_sale_start_date: <%= ENV['STA_PRE_SALE_START_DATE'] %>
      public_sale_start_date: <%= ENV['STA_PUBLIC_SALE_START_DATE'] %>
      public_sale_end_date: <%= ENV['STA_PUBLIC_SALE_END_DATE'] %>

  recaptcha:
    site_key: <%= ENV['STA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['STA_RECAPTCHA_SECRET'] %>