constants:
  kms:
    login:
      arn: <%= ENV['STA_LOGIN_KMS_ARN']%>
      id: <%= ENV['STA_LOGIN_KMS_ID']%>
    kyc:
      arn: <%= ENV['STA_KYC_KMS_ARN']%>
      id: <%= ENV['STA_KYC_KMS_ID']%>

  cynopsis:
    base_url: <%= ENV['STA_CYNOPSIS_BASE_URL']%>
    token: <%= ENV['STA_CYNOPSIS_TOKEN']%>
    domain_name: <%= ENV['STA_CYNOPSIS_DOMAIN_NAME']%>

  aws:
    region: <%= ENV['STA_DEFAULT_AWS_REGION']%>
    admin:
      access_key: <%= ENV['STA_ADMIN_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_ADMIN_AWS_SECRET_KEY']%>
    user:
      access_key: <%= ENV['STA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_USER_AWS_SECRET_KEY']%>

  pepo_campaigns:
    api:
      key: <%= ENV['STA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['STA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['STA_CAMPAIGN_BASE_URL']%>
      version: 'v1'
    list_ids:
      master_list: <%= ENV['STA_CAMPAIGN_MASTER_LIST']%>

  redis:
    url: <%= ENV['STA_REDIS_ENDPOINT'] %>

  s3:
    kyc_bucket: <%= ENV['STA_KYC_S3_BUCKET_NAME']%>

  st_token_sale:
    active_status: <%= ENV['ST_TOKEN_SALE_ACTIVE_STATUS']%>
    pre_sale_register_start_date:  <%= ENV['ST_PRE_SALE_REGISTER_START_DATE'] %>
    pre_sale_two_register_start_date:  <%= ENV['ST_PRE_SALE_TWO_REGISTER_START_DATE'] %>
    public_sale_register_start_date:  <%= ENV['ST_PUBLIC_SALE_REGISTER_START_DATE'] %>