constants:
  kms:
    login:
      id: <%= ENV['STA_LOGIN_KMS_ID']%>
    kyc:
      id: <%= ENV['STA_KYC_KMS_ID']%>
    entity_association:
      id: <%= ENV['STA_ENTITY_ASSOC_ID']%>
    saas:
      id: <%= ENV['STA_SAAS_KMS_ID']%>

  aws:
    region: <%= ENV['STA_DEFAULT_AWS_REGION']%>
    admin:
      access_key: <%= ENV['STA_ADMIN_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_ADMIN_AWS_SECRET_KEY']%>
    user:
      access_key: <%= ENV['STA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_USER_AWS_SECRET_KEY']%>
    saas:
      access_key: <%= ENV['STA_SAAS_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_SAAS_AWS_SECRET_KEY']%>

  pepo_campaigns:
    api:
      key: <%= ENV['STA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['STA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['STA_CAMPAIGN_BASE_URL']%>
      version: 'v2'
    list_ids:
      master_list: <%= ENV['STA_CAMPAIGN_MASTER_LIST']%>
      kyc_product_list: <%= ENV['STA_CAMPAIGN_KYC_PRODUCT_LIST']%>
      alpha_4_users_list: <%= ENV['STA_CAMPAIGN_ALPHA4_USER_LIST']%>

  redis:
    url: <%= ENV['STA_REDIS_ENDPOINT'] %>

  s3:
    kyc_bucket: <%= ENV['STA_KYC_S3_BUCKET_NAME']%>
    report_bucket: <%= ENV['STA_REPORTS_S3_BUCKET_NAME']%>
    client_assets_bucket: <%= ENV['STA_CLIENT_ASSETS_S3_BUCKET_NAME']%>
    client_assets_cdn: <%= ENV['STA_CLIENT_ASSETS_CDN_URL']%>

  local_path:
    geo_ip_file: <%= ENV['STA_GEOIP_FILE_WITH_PATH'] %>

  st_token_sale:
    critical_details:
      simple_token_contract_address: '<%= ENV['STA_SIMPLE_TOKEN_CONTRACT_ADDRESS']%>'
    default_client_id: <%= ENV['SIMPLE_TOKEN_SALE_CLIENT_ID'] %>

  st_foundation_contracts:
    token_sale: '<%= ENV['STA_TOKEN_SALE_CONTRACT_ADDRESS'] %>'

  recaptcha:
    secret_key: <%= ENV['STA_RECAPTCHA_SECRET'] %>

  secret_encryptor:
    cookie_secret_key: <%= ENV['STA_COOKIE_SECRET_KEY'] %>
    email_tokens_decriptor_key: <%= ENV['STA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>
    user_extended_detail_secret_key: <%= ENV['STA_USER_EXTENDED_DETAIL_SECRET_KEY'] %>
    ethereum_deposit_address_secret_key: <%= ENV['STA_ETHEREUM_DEPOSIT_ADDRESS_SECRET_KEY'] %>
    webhook_event_secret_key: <%= ENV['WEBHOOK_EVENT_SECRET_KEY'] %>
    memcache_encryption_key: <%= ENV['MEMCACHE_ENCRYPTION_KEY'] %>

  private_ops:
    base_url: <%= ENV['STA_PRIVATE_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PRIVATE_OPS_API_SECRET_KEY'] %>

  public_ops:
    base_url: <%= ENV['STA_PUBLIC_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PUBLIC_OPS_API_SECRET_KEY'] %>

  ost_kyc_api:
    sandbox:
      rsa_public_key: <%= ENV['STA_KYC_API_SANDBOX_ENV_RSA_PUBLIC_KEY'] %>
    main:
      rsa_private_key: <%= ENV['STA_KYC_API_MAIN_ENV_RSA_PRIVATE_KEY'] %>

  memcached:
    instances: <%= ENV['STA_MEMCACHED_INSTANCES'] %>

  pipedrive:
    deals_end_point: 'https://api.pipedrive.com/v1/deals'
    api_token: <%= ENV['PIPEDRIVE_API_TOKEN'] %>
    project_description_key: <%= ENV['PROJECT_DESCRIPTION_PD_KEY'] %>
    kyc_init_stage_id: <%= ENV['KYC_INIT_STAGE_ID'] %>
    partners_init_stage_id: <%= ENV['PARTNERS_INIT_STAGE_ID'] %>
    utm_source_key: <%= ENV['UTM_SOURCE_PD_KEY'] %>
    default_kyc_deal_owner: <%= ENV['PD_DEFAULT_KYC_DEAL_OWNER'] %>
    default_partner_deal_owner: <%= ENV['PD_DEFAULT_PARTNER_DEAL_OWNER'] %>

  google_vision:
    project_id: <%= ENV['VISION_PROJECT_ID'] %>
    credentials_json: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>

  kyc_app:
    shared_directory: <%= ENV['APP_SHARED_DIRECTORY'] %>
    addendum_client_ids: <%= ENV['ADDENDUM_CLIENT_IDS'] %>

  kyc_api_base_domain:
    development: "http://kyc.developmentost.com:8080"
    staging: "https://kyc.stagingost.com"
    sandbox: "https://kyc.sandboxost.com"
    production: "https://kyc.ost.com"

  gas_estimation_constants:
    max_gas_price: <%= ENV['MAX_GAS_FOR_TRANSACTION_GWEI'] %>
    min_gas_price: <%= ENV['MIN_GAS_FOR_TRANSACTION_GWEI'] %>
    buffer_gas: <%= ENV['BUFFER_GAS_FOR_TRANSACTION_GWEI'] %>
    default_gas_price: <%= ENV['DEFAULT_GAS_FOR_TRANSACTION_GWEI'] %>