constants:
  kms:
    login:
      arn: <%= ENV['STA_LOGIN_KMS_ARN']%>
      id: <%= ENV['STA_LOGIN_KMS_ID']%>
    kyc:
      arn: <%= ENV['STA_KYC_KMS_ARN']%>
      id: <%= ENV['STA_KYC_KMS_ID']%>
    entity_association:
      arn: <%= ENV['STA_ENTITY_ASSOC_ARN']%>
      id: <%= ENV['STA_ENTITY_ASSOC_ID']%>
    saas:
      arn: <%= ENV['STA_SAAS_KMS_ARN']%>
      id: <%= ENV['STA_SAAS_KMS_ID']%>

  cynopsis:
    base_url: <%= ENV['STA_CYNOPSIS_BASE_URL']%>
    token: <%= ENV['STA_CYNOPSIS_TOKEN']%>
    domain_name: <%= ENV['STA_CYNOPSIS_DOMAIN_NAME']%>

  aws:
    region: <%= ENV['STA_DEFAULT_AWS_REGION']%>
    admin:
      access_key: <%= ENV['STA_ADMIN_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_ADMIN_AWS_SECRET_KEY']%>
    user:
      access_key: <%= ENV['STA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_USER_AWS_SECRET_KEY']%>
    saas:
      access_key: <%= ENV['STA_SAAS_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_SAAS_AWS_SECRET_KEY']%>

  pepo_campaigns:
    api:
      key: <%= ENV['STA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['STA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['STA_CAMPAIGN_BASE_URL']%>
      version: 'v2'
    list_ids:
      master_list: <%= ENV['STA_CAMPAIGN_MASTER_LIST']%>

  redis:
    url: <%= ENV['STA_REDIS_ENDPOINT'] %>

  s3:
    kyc_bucket: <%= ENV['STA_KYC_S3_BUCKET_NAME']%>
    report_bucket: <%= ENV['STA_REPORTS_S3_BUCKET_NAME']%>

  local_path:
    geo_ip_file: <%= ENV['STA_GEOIP_FILE_WITH_PATH'] %>

  st_token_sale:
    critical_details:
      active_status: <%= ENV['STA_TOKEN_SALE_ACTIVE_STATUS']%>
      token_sale_ethereum_address: '<%= ENV['STA_TOKEN_SALE_CONTRACT_ADDRESS']%>'
      simple_token_contract_address: '<%= ENV['STA_SIMPLE_TOKEN_CONTRACT_ADDRESS']%>'
    user_register_dates:
      early_access_register_end_date:  <%= ENV['STA_EARLY_ACCESS_REGISTER_END_DATE'] %>
    sale_dates:
      early_access_start_date: <%= ENV['STA_EARLY_ACCESS_START_DATE'] %>
      general_access_start_date: <%= ENV['STA_GENERAL_ACCESS_START_DATE'] %>
      general_access_end_date: <%= ENV['STA_GENERAL_ACCESS_END_DATE'] %>
    default_client_id: <%= ENV['SIMPLE_TOKEN_SALE_CLIENT_ID'] %>

  st_foundation_contracts:
    token_sale: '<%= ENV['STA_TOKEN_SALE_CONTRACT_ADDRESS'] %>'

  recaptcha:
    site_key: <%= ENV['STA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['STA_RECAPTCHA_SECRET'] %>

  secret_encryptor:
    cookie_secret_key: <%= ENV['STA_COOKIE_SECRET_KEY'] %>
    email_tokens_decriptor_key: <%= ENV['STA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>
    user_extended_detail_secret_key: <%= ENV['STA_USER_EXTENDED_DETAIL_SECRET_KEY'] %>
    ethereum_deposit_address_secret_key: <%= ENV['STA_ETHEREUM_DEPOSIT_ADDRESS_SECRET_KEY'] %>

  private_ops:
    base_url: <%= ENV['STA_PRIVATE_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PRIVATE_OPS_API_SECRET_KEY'] %>

  public_ops:
    base_url: <%= ENV['STA_PUBLIC_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PUBLIC_OPS_API_SECRET_KEY'] %>

  memcached:
    instances: <%= ENV['STA_MEMCACHED_INSTANCES'] %>

  pipedrive:
    deals_end_point: 'https://api.pipedrive.com/v1/deals'
    api_token: <%= ENV['PIPEDRIVE_API_TOKEN'] %>
    project_description_key: <%= ENV['PROJECT_DESCRIPTION_PD_KEY'] %>
    token_sale_start_date_key: <%= ENV['TOKEN_SALE_START_DATE_PD_KEY'] %>
    token_sale_end_date_key: <%= ENV['TOKEN_SALE_END_DATE_PD_KEY'] %>
    need_front_end_key: <%= ENV['NEED_FRONT_END_PD_KEY'] %>
    applicant_volume_key: <%= ENV['APPLICANT_VOLUME_PD_KEY'] %>
    kyc_init_stage_id: <%= ENV['KYC_INIT_STAGE_ID'] %>
    partners_init_stage_id: <%= ENV['PARTNERS_INIT_STAGE_ID'] %>
    utm_source_key: <%= ENV['UTM_SOURCE_PD_KEY'] %>
