constants:
  kms:
    login:
      arn: <%= ENV['STA_LOGIN_KMS_ARN']%>
      id: <%= ENV['STA_LOGIN_KMS_ID']%>
    kyc:
      arn: <%= ENV['STA_KYC_KMS_ARN']%>
      id: <%= ENV['STA_KYC_KMS_ID']%>

  cynopsis:
    base_url: <%= ENV['STA_CYNOPSIS_BASE_URL']%>
    token: <%= ENV['STA_CYNOPSIS_TOKEN']%>
    domain_name: <%= ENV['STA_CYNOPSIS_DOMAIN_NAME']%>

  aws:
    region: <%= ENV['STA_DEFAULT_AWS_REGION']%>
    admin:
      access_key: <%= ENV['STA_ADMIN_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_ADMIN_AWS_SECRET_KEY']%>
    user:
      access_key: <%= ENV['STA_USER_AWS_ACCESS_KEY']%>
      secret_key: <%= ENV['STA_USER_AWS_SECRET_KEY']%>

  pepo_campaigns:
    api:
      key: <%= ENV['STA_CAMPAIGN_CLIENT_KEY']%>
      secret: <%= ENV['STA_CAMPAIGN_CLIENT_SECRET']%>
      base_url: <%= ENV['STA_CAMPAIGN_BASE_URL']%>
      version: 'v1'
    list_ids:
      master_list: <%= ENV['STA_CAMPAIGN_MASTER_LIST']%>
      pos_list: <%= ENV['STA_CAMPAIGN_POS_LIST']%>

  redis:
    url: <%= ENV['STA_REDIS_ENDPOINT'] %>

  s3:
    kyc_bucket: <%= ENV['STA_KYC_S3_BUCKET_NAME']%>

  local_path:
    geo_ip_file: <%= ENV['STA_GEOIP_FILE_WITH_PATH'] %>

  st_token_sale:
    critical_details:
      active_status: <%= ENV['STA_TOKEN_SALE_ACTIVE_STATUS']%>
      foundation_ethereum_address: <%= ENV['STA_FOUNDATION_ETHEREUM_ADDRESS']%>
    user_register_dates:
      early_access_register_end_date:  <%= ENV['STA_EARLY_ACCESS_REGISTER_END_DATE'] %>
    sale_dates:
      early_access_start_date: <%= ENV['STA_EARLY_ACCESS_START_DATE'] %>
      general_access_start_date: <%= ENV['STA_GENERAL_ACCESS_START_DATE'] %>
      general_access_end_date: <%= ENV['STA_GENERAL_ACCESS_END_DATE'] %>

  recaptcha:
    site_key: <%= ENV['STA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['STA_RECAPTCHA_SECRET'] %>

  secret_encryptor:
    cookie_secret_key: <%= ENV['STA_COOKIE_SECRET_KEY'] %>
    email_tokens_decriptor_key: <%= ENV['STA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>

  private_ops:
    base_url: <%= ENV['STA_PRIVATE_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PRIVATE_OPS_API_SECRET_KEY'] %>

  public_ops:
    base_url: <%= ENV['STA_PUBLIC_OPS_API_BASE_URL'] %>
    secret_key: <%= ENV['STA_PUBLIC_OPS_API_SECRET_KEY'] %>