default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  username: <%= ENV['STA_DEFAULT_DB_USER']%>
  password: <%= ENV['STA_DEFAULT_DB_PASSWORD']%>
  host: <%= ENV['STA_DEFAULT_DB_HOST']%>

<%= Rails.env%>:
  <<: *default
  database: simple_token_api_<%= Rails.env%>

simple_token_admin_<%= Rails.env%>:
  <<: *default
  database: simple_token_admin_<%= Rails.env%>

simple_token_user_<%= Rails.env%>:
  <<: *default
  database: simple_token_user_<%= Rails.env%>

simple_token_email_<%= Rails.env%>:
  <<: *default
  database: simple_token_email_<%= Rails.env%>

simple_token_log_<%= Rails.env%>:
  <<: *default
  database: simple_token_log_<%= Rails.env%>

simple_token_contract_interactions_<%= Rails.env%>:
  <<: *default
  database: simple_token_contract_interactions_<%= Rails.env%>

simple_token_client_<%= Rails.env%>:
  <<: *default
  database: simple_token_client_<%= Rails.env%>

simple_token_image_process_poc_<%= Rails.env%>:
  <<: *default
  database: simple_token_image_process_poc_<%= Rails.env%>

simple_token_customization_<%= Rails.env%>:
  <<: *default
  database: simple_token_customization_<%= Rails.env%>

simple_token_billing_<%= Rails.env%>:
  <<: *default
  database: simple_token_billing_<%= Rails.env%>