user:
  user_details:
    key_template: 'u_det_%{id}'
    expiry_in_seconds: 86400

  user_kyc_details:
    key_template: 'u_kyc_det_%{user_id}'
    expiry_in_seconds: 86400

  user_kyc_comparison_detail:
    key_template: 'user_kyc_comparison_detail_by_ued_%{user_extended_detail_id}'
    expiry_in_seconds: 86400

alternate_token:
  alternate_token_details:
    key_template: 'alternate_token_details_%{id}'
    expiry_in_seconds: 86400

token_sale:
  sale_details:
    key_template: 'token_sale_stats'
    expiry_in_seconds: 30
    used_in_shared_env: true

  pre_sale:
    key_template: 'token_sale_pre_sale'
    expiry_in_seconds: 86400

  sale_ended:
    key_template: 'token_sale_sale_ended'
    expiry_in_seconds: 86400

client:
  client_details:
    key_template: 'client_detail_%{id}'
    expiry_in_seconds: 86400

  api_key_details:
    key_template: 'client_api_key_detail_%{api_key}'
    expiry_in_seconds: 86400

  client_cynopsis_details:
    key_template: 'client_cynopsis_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_whitelist_details:
    key_template: 'client_whitelist_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_pepo_campaign_details:
    key_template: 'client_pepo_campaign_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_web_host_details_by_cid:
    key_template: 'client_web_host_details_by_cid_%{client_id}'
    expiry_in_seconds: 86400

  client_web_host_details_by_domain:
    key_template: 'client_web_host_details_by_domain_%{domain}'
    expiry_in_seconds: 86400

  client_token_sale_details:
    key_template: 'client_token_sale_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_kyc_config_details:
    key_template: 'client_kyc_config_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_template_type_details:
    key_template: 'client_template_type_details_%{client_id}_%{template_type}'
    expiry_in_seconds: 86400

  client_setting_detail:
    key_template: 'client_setting_detail_%{client_id}_%{entity_type}'
    expiry_in_seconds: 86400

  client_kyc_pass_active_setting:
    key_template: 'client_kyc_pass_active_setting_%{client_id}'
    expiry_in_seconds: 86400

admin:
  admin_details:
    key_template: 'admin_det_%{id}'
    expiry_in_seconds: 86400
  admin_secret_details:
    key_template: 'admin_secrets_det_%{id}'
    expiry_in_seconds: 86400

customization:
  entity_draft:
    key_template: 'entity_draft_%{id}'
    expiry_in_seconds: 86400

  entity_group:
    key_template: 'entity_group_%{id}'
    expiry_in_seconds: 86400

  group_entities:
    key_template: 'group_entities_%{entity_group_id}'
    expiry_in_seconds: 86400

general:
  current_gas_price:
    key_template: 'current_gas_price'
    expiry_in_seconds: 900