user:
  user_details:
    key_template: 'u_det_%{id}'
    expiry_in_seconds: 86400
  user_kyc_details:
    key_template: 'u_kyc_det_%{user_id}'
    expiry_in_seconds: 86400

alternate_token:
  alternate_token_details:
    key_template: 'alternate_token_details_%{id}'
    expiry_in_seconds: 86400

token_sale:
  sale_details:
    key_template: 'token_sale_stats'
    expiry_in_seconds: 30
    used_in_shared_env: true

  pre_sale:
    key_template: 'token_sale_pre_sale'
    expiry_in_seconds: 86400

  sale_ended:
    key_template: 'token_sale_sale_ended'
    expiry_in_seconds: 86400

client:
  client_details:
    key_template: 'client_detail_%{id}'
    expiry_in_seconds: 86400

  api_key_details:
    key_template: 'client_api_key_detail_%{api_key}'
    expiry_in_seconds: 86400

  client_cynopsis_details:
    key_template: 'client_cynopsis_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_whitelist_details:
    key_template: 'client_whitelist_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_pepo_campaign_details:
    key_template: 'client_pepo_campaign_detail_%{client_id}'
    expiry_in_seconds: 86400

  client_admins:
    key_template: 'client_admins_%{admin_id}'
    expiry_in_seconds: 86400
