user:
  user_details:
    key_template: 'u_det_%{id}'
    expiry_in_hours: 3600
  user_kyc_details:
    key_template: 'u_kyc_det_%{user_id}'
    expiry_in_hours: 3600

token_sale:
  sale_details:
    key_template: 'token_sale_start_end_details'
    expiry_in_hours: 3600