shards:
  sql_config:
    db:
      shard_1:
        model_suffix: 'shard1'
        db: ost_kyc_user_shard_1

      shard_2:
        model_suffix: 'shard2'
        db: ost_kyc_user_shard_2

    models:
      'User':
        table: 'users'

      'UserSecret':
        table: 'user_secrets'

      'UserKycDetail':
        table: 'user_kyc_details'

      'UserKycComparisonDetail':
        table: 'user_kyc_comparison_details'

      'UserExtendedDetail':
        table: 'user_extended_details'

      'Md5UserExtendedDetail':
        table: 'md5_user_extended_details'

      'DeletedUser':
        table: 'deleted_users'