sql_shard_config:
  shards:
    shard_1:
      id: 1
      model_suffix: 'shard1'

    shard_2:
      id: 2
      model_suffix: 'shard2'

  models:
      user:
        'User':
          table: 'users'

        'UserSecret':
          table: 'user_secrets'

        'UserKycDetail':
          table: 'user_kyc_details'

        'UserKycComparisonDetail':
          table: 'user_kyc_comparison_details'

        'UserExtendedDetail':
          table: 'user_extended_details'

        'Md5UserExtendedDetail':
          table: 'md5_user_extended_details'

        'DeletedUser':
          table: 'deleted_users'

      user_log:
        'UserUtmLog':
          table: 'user_utm_logs'

        'UserEmailDuplicationLog':
          table: 'user_email_duplication_logs'

        'UserActivityLog':
          table: 'user_activity_logs'

        'UserKycDuplicationLog':
          table: 'user_kyc_duplication_logs'

        'EditKycRequest':
          table: 'edit_kyc_requests'

        'ImageProcessingLog':
          table: 'image_processing_logs'

      aml:
        'AmlSearch':
          table: 'aml_searches'

        'AmlMatch':
          table: 'aml_matches'

        'AmlLog':
          table: 'aml_logs'